def CHR_SETARM(arg1: Value32, arg2: Nullable32, arg3: Nullable32):
    LOAD_STACK(-4)
    PUSH_INT(0)
    EQ()
    POP_JMP_ZERO(loc_EF9DC)

    label('loc_EF991')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(0)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(0)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EF9DC')
    
    LOAD_STACK(-4)
    PUSH_INT(1)
    EQ()
    POP_JMP_ZERO(loc_EFA38)

    label('loc_EF9ED')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(1)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(1)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFA38')
    
    LOAD_STACK(-4)
    PUSH_INT(2)
    EQ()
    POP_JMP_ZERO(loc_EFA94)

    label('loc_EFA49')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(2)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(2)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFA94')
    
    LOAD_STACK(-4)
    PUSH_INT(3)
    EQ()
    POP_JMP_ZERO(loc_EFAF0)

    label('loc_EFAA5')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(3)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(3)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFAF0')
    
    LOAD_STACK(-4)
    PUSH_INT(4)
    EQ()
    POP_JMP_ZERO(loc_EFB4C)

    label('loc_EFB01')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(4)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(4)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFB4C')
    
    LOAD_STACK(-4)
    PUSH_INT(5)
    EQ()
    POP_JMP_ZERO(loc_EFBA8)

    label('loc_EFB5D')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(5)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(5)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFBA8')
    
    LOAD_STACK(-4)
    PUSH_INT(6)
    EQ()
    POP_JMP_ZERO(loc_EFC04)

    label('loc_EFBB9')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(6)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(6)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFC04')
    
    LOAD_STACK(-4)
    PUSH_INT(7)
    EQ()
    POP_JMP_ZERO(loc_EFC60)

    label('loc_EFC15')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(7)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(7)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFC60')
    
    LOAD_STACK(-4)
    PUSH_INT(106)
    EQ()
    POP_JMP_ZERO(loc_EFCBC)

    label('loc_EFC71')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(106)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(106)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFCBC')
    
    LOAD_STACK(-4)
    PUSH_INT(105)
    EQ()
    POP_JMP_ZERO(loc_EFD18)

    label('loc_EFCCD')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(105)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(105)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFD18')
    
    LOAD_STACK(-4)
    PUSH_INT(104)
    EQ()
    POP_JMP_ZERO(loc_EFD74)

    label('loc_EFD29')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(104)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(104)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFD74')
    
    LOAD_STACK(-4)
    PUSH_INT(118)
    EQ()
    POP_JMP_ZERO(loc_EFDD0)

    label('loc_EFD85')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(118)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(118)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFDD0')
    
    LOAD_STACK(-4)
    PUSH_INT(114)
    EQ()
    POP_JMP_ZERO(loc_EFE2C)

    label('loc_EFDE1')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(114)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(114)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFE2C')
    
    LOAD_STACK(-4)
    PUSH_INT(108)
    EQ()
    POP_JMP_ZERO(loc_EFE88)

    label('loc_EFE3D')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(108)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(108)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFE88')
    
    LOAD_STACK(-4)
    PUSH_INT(101)
    EQ()
    POP_JMP_ZERO(loc_EFEE4)

    label('loc_EFE99')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(101)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(101)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFEE4')
    
    LOAD_STACK(-4)
    PUSH_INT(102)
    EQ()
    POP_JMP_ZERO(loc_EFF40)

    label('loc_EFEF5')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(102)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(102)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFF40')
    
    LOAD_STACK(-4)
    PUSH_INT(103)
    EQ()
    POP_JMP_ZERO(loc_EFF9C)

    label('loc_EFF51')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(103)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(103)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFF9C')
    
    LOAD_STACK(-4)
    PUSH_INT(100)
    EQ()
    POP_JMP_ZERO(loc_EFFF8)

    label('loc_EFFAD')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(100)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(100)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_EFFF8')
    
    LOAD_STACK(-4)
    PUSH_INT(137)
    EQ()
    POP_JMP_ZERO(loc_F0054)

    label('loc_F0009')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(137)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(137)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_F0054')
    
    LOAD_STACK(-4)
    PUSH_INT(138)
    EQ()
    POP_JMP_ZERO(loc_F00B0)

    label('loc_F0065')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(138)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(138)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_F00B0')
    
    LOAD_STACK(-4)
    PUSH_INT(139)
    EQ()
    POP_JMP_ZERO(loc_F010C)

    label('loc_F00C1')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    PUSH_INT(139)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniBtlWait")
    PUSH_INT(2)
    PUSH_INT(139)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_F010C')
    
    PUSH_FLOAT(1.0)
    PUSH_INT(-1)
    PUSH_STR("AniAttachWeapon")
    PUSH_INT(2)
    LOAD_STACK(-20)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    LOAD_STACK(-12)
    LOAD_STACK(-12)
    PUSH_STR("AniEvBtlWait")
    PUSH_INT(2)
    LOAD_STACK(-20)
    SYSCALL(1, 0x2F, 0x05)
    POP(20)
    JMP(loc_F0150)

    label('loc_F0150')
    
    PUSH_RAW(RawInt(0x00000000))
    SET_REG(0)
    POP(12)
    RETURN()

def EV_02_63_02_SELECT_00():
    DEBUG_SET_LINENO(26456)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FBDF)
    PUSH_INT(0)
    CALL(global_work)

    label('loc_15FBDF')
    
    GET_REG(0)
    PUSH_INT(-1)
    EQ()
    POP_JMP_ZERO(loc_15FD2D)

    label('loc_15FBED')
    
    DEBUG_SET_LINENO(26457)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FC17)
    PUSH_INT(28)
    PUSH_INT(0)
    PUSH_INT(2)
    PUSH_INT(0)
    CALL(menu_create)

    label('loc_15FC17')
    
    DEBUG_SET_LINENO(26458)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FC3B)
    PUSH_INT(0)
    PUSH_STR("那好，我也去！")
    PUSH_INT(0)
    CALL(menu_additem)

    label('loc_15FC3B')
    
    DEBUG_SET_LINENO(26459)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FC5F)
    PUSH_INT(1)
    PUSH_STR("这、这家伙也太乱来了……")
    PUSH_INT(0)
    CALL(menu_additem)

    label('loc_15FC5F')
    
    DEBUG_SET_LINENO(26461)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FC8F)
    PUSH_STR("")
    PUSH_INT(0)
    PUSH_INT(-1)
    PUSH_INT(-1)
    PUSH_INT(0)
    CALL(menu_open)

    label('loc_15FC8F')
    
    DEBUG_SET_LINENO(26464)
    PUSH_RAW(RawInt(0x00000000))
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FCAD)
    PUSH_INT(0)
    CALL(menu_wait)

    label('loc_15FCAD')
    
    GET_REG(0)
    POP_TO(-4)
    DEBUG_SET_LINENO(26465)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FCCC)
    PUSH_INT(0)
    CALL(menu_close)

    label('loc_15FCCC')
    
    DEBUG_SET_LINENO(26467)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FCE4)
    PUSH_INT(0)
    CALL(menu_is_canceled)

    label('loc_15FCE4')
    
    GET_REG(0)
    POP_JMP_ZERO(loc_15FD0E)

    label('loc_15FCEB')
    
    DEBUG_SET_LINENO(26468)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FD09)
    PUSH_INT(1)
    PUSH_INT(0)
    CALL(set_global_work)

    label('loc_15FD09')
    
    JMP(loc_15FD2B)

    label('loc_15FD0E')
    
    DEBUG_SET_LINENO(26470)
    PUSH_CURRENT_FUNC_ID()
    PUSH_RET_ADDR(loc_15FD2B)
    LOAD_STACK(-12)
    PUSH_INT(0)
    CALL(set_global_work)

    label('loc_15FD2B')
    
    POP(4)
    JMP(loc_15FD2D)

    label('loc_15FD2D')
    
    DEBUG_SET_LINENO(26473)
    PUSH_RAW(RawInt(0x00000000))
    SET_REG(0)
    RETURN()

